[[sources]]
url = "https://github.com/input-output-hk/iohk-monitoring-framework/tarball/46f994e216a1f8b36fe4669b47b2a7011b0e153c"
subdirs = [
  "contra-tracer",
  "iohk-monitoring",
  "tracer-transformers",
  "plugins/backend-ekg",
]

[[sources]]
url = "https://github.com/input-output-hk/plutus/tarball/cc72a56eafb02333c96f662581b57504f8f8992f"
subdirs = [
  "plutus-core",
  "plutus-ledger-api",
  "plutus-tx",
  "plutus-tx-plugin",
  "prettyprinter-configurable",
  "stubs/plutus-ghc-stub",
  "word-array",
]

[[sources]]
url = "https://github.com/Quid2/flat/tarball/ee59880f47ab835dbd73bea0847dab7869fc20d8"

[[sources]]
url = "https://github.com/input-output-hk/servant-purescript/tarball/44e7cacf109f84984cd99cd3faf185d161826963"

[[sources]]
url = "https://github.com/input-output-hk/purescript-bridge/tarball/47a1f11825a0f9445e0f98792f79172efef66c00"

[[sources]]
url = "https://github.com/input-output-hk/cardano-wallet/tarball/a5085acbd2670c24251cf8d76a4e83c77a2679ba"
subdirs = [
  "lib/cli",
  "lib/core",
  "lib/core-integration",
  "lib/dbvar",
  "lib/launcher",
  "lib/numeric",
  "lib/shelley",
  "lib/strict-non-empty-containers",
  "lib/test-utils",
  "lib/text-class"
]

[[sources]]
url = "https://github.com/input-output-hk/cardano-node/tarball/814df2c146f5d56f8c35a681fe75e85b905aed5d"
subdirs = [
  "cardano-api"
]

[[sources]]
url = "https://github.com/input-output-hk/cardano-ledger/tarball/1a9ec4ae9e0b09d54e49b2a40c4ead37edadcce5"
subdirs = [
  "eras/alonzo/impl",
 "eras/byron/chain/executable-spec",
 "eras/byron/crypto",
 "eras/byron/crypto/test",
 "eras/byron/ledger/executable-spec",
 "eras/byron/ledger/impl",
 "eras/byron/ledger/impl/test",
 "eras/shelley/impl",
 "eras/shelley/test-suite",
 "eras/shelley-ma/impl",
 "libs/cardano-data",
 "libs/cardano-ledger-core",
 "libs/cardano-ledger-pretty",
 "libs/cardano-protocol-tpraos",
 "libs/compact-map",
 "libs/non-integral",
 "libs/set-algebra",
 "libs/small-steps",
 "libs/small-steps-test"
]

[[sources]]
url = "https://github.com/input-output-hk/ouroboros-network/tarball/d2d219a86cda42787325bb8c20539a75c2667132"
subdirs = [
  "io-classes",
  "io-sim",
  "monoidal-synchronisation",
  "network-mux",
  "ntp-client",
  "ouroboros-consensus",
  "ouroboros-consensus-byron",
  "ouroboros-consensus-cardano",
  "ouroboros-consensus-protocol",
  "ouroboros-consensus-shelley",
  "ouroboros-network",
  "ouroboros-network-framework",
  "ouroboros-network-testing",
  "strict-stm",
  "typed-protocols",
  "typed-protocols-cborg",
  "typed-protocols-examples"
]

[[sources]]
url = "https://github.com/input-output-hk/cardano-base/tarball/41545ba3ac6b3095966316a99883d678b5ab8da8"
subdirs = [
  "base-deriving-via",
  "binary",
  "binary/test",
  "cardano-crypto-class",
  "cardano-crypto-praos",
  "measures",
  "orphans-deriving-via",
  "slotting",
  "strict-containers"
]

[[sources]]
url = "https://github.com/input-output-hk/cardano-prelude/tarball/bb4ed71ba8e587f672d06edf9d2e376f4b055555"
subdirs = [
  "cardano-prelude",
  "cardano-prelude-test"
]

[[sources]]
url = "https://github.com/input-output-hk/cardano-crypto/tarball/f73079303f663e028288f9f4a9e08bcca39a923e"

[[sources]]
url = "https://github.com/input-output-hk/cardano-addresses/tarball/71006f9eb956b0004022e80aadd4ad50d837b621"
subdirs = [
  "command-line",
  "core"
]

[[sources]]
url = "https://github.com/input-output-hk/goblins/tarball/cde90a2b27f79187ca8310b6549331e59595e7ba"

[[sources]]
url = "https://github.com/input-output-hk/Win32-network/tarball/3825d3abf75f83f406c1f7161883c438dac7277d"

[[sources]]
url = "https://github.com/input-output-hk/plutus-apps/tarball/dc04b5491ce6e3f830fc26d74191d3583e7816ec"
subdirs = [
  "doc",
  "freer-extras",
  "playground-common",
  "plutus-chain-index",
  "plutus-chain-index-core",
  "plutus-contract",
  "plutus-ledger",
  "plutus-ledger-constraints",
  "plutus-pab",
  "plutus-pab-executables",
  "plutus-playground-server",
  "plutus-use-cases",
  "quickcheck-dynamic",
  "web-ghc"
]
