name: Publish repository

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: Build repository
        id: build-repository
        uses: andreabedini/foliage@main
        env:
          KEYS: ${{ secrets.KEYS }}

      - name: Copy static web assets
        run: |
          cp static/index.html ${{ steps.build-repository.outputs.repository-path }}
          cp README.md ${{ steps.build-repository.outputs.repository-path }}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages
          folder: ${{ steps.build-repository.outputs.repository-path }}
