name: Publish Hackage repository

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - id: setup-haskell
        uses: haskell/actions/setup@v1
        with:
          ghc-version: '8.10.7'

      - name: Setup cache for cabal store
        uses: actions/cache@v2
        with:
          path: ${{ steps.setup-haskell.outputs.cabal-store }}
          key: cabal-store-${{ github.sha }}
          restore-keys: cabal-store-

      - name: Install hackage-repo-tool
        run: |
          cabal install hackage-repo-tool
          echo "$HOME/.cabal/bin" >> $GITHUB_PATH

      - name: Setup cache for the repository
        uses: actions/cache@v2
        with:
          path: ./repo
          key: hackage-repo-${{ github.sha }}
          restore-keys: hackage-repo-

      - name: Build
        run: ./build.sh
        env:
          KEYS: ${{ secrets.KEYS }}

      - name: Copy static web assets
        run: |
          cp static/index.html ./repo
          cp README.md ./repo

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages
          folder: ./repo
